#!groovy

properties([
    parameters([
        string(defaultValue: 'aaksyonov/vpuEntrypoint',
               description: 'Pipeline shared library version (branch/tag/commit). Determined automatically if empty',
               name: 'library_version')
    ])
])

@Library('common@aaksyonov/vpuEntrypoint') _

loadVPUXLibrary {
    vpuPrecommit.runOvPrecommit(this)
}



