#!groovy

properties([
    parameters([
        string(defaultValue: '',
               description: 'Pipeline shared library version (branch/tag/commit). Determined automatically if empty',
               name: 'library_version')
    ])
])

loadVPUXLibrary {
    @Library('common@aaksyonov/vpuEntrypoint') _
    vpuEntrypoint(this)
}
