#!groovy
@Library('common@aaksyonov/vpuEntrypoint') _

properties([
    parameters([
        string(defaultValue: '',
               description: 'Pipeline shared library version (branch/tag/commit). Determined automatically if empty',
               name: 'library_version')
    ])
])

loadVPUXLibrary {
    vpuEntrypoint(this)
}
