name: PR Commits
on: [pull_request]

jobs:
  Checks:
    permissions: write-all
    runs-on: ubuntu-22.04
    steps:
      - name: Clone current repo
        uses: actions/checkout@v3

      - name: Clone OpenVINO
        uses: snow-actions/sparse-checkout@v1.2.0
        with:
          repository: akladiev/openvino
          path: openvino
          ref: label_by_pr_author
          patterns: |
            .github/github_org_control

      - name: Install dependencies
        run: python3 -m pip install -r openvino/.github/github_org_control/requirements.txt

      - name: Label commit by PR author
        run: python3 openvino/.github/github_org_control/check_pr.py --pr=${{ github.event.number }} --cfg-file=.github/workflows/config.json
        env:
          GITHUB_TOKEN: ${{ secrets.ORG_TOKEN }}
