name: Check Smart CI
on:
  pull_request

jobs:
  Smart_CI:
    runs-on: ubuntu-latest
    outputs:
      affected_components: "${{ steps.smart_ci.outputs.affected_components }}"
    steps:
      - name: Get affected components
        id: smart_ci
        uses: akladiev/testrepo/.github/actions/affected-components@0.1.1
        with:
          repository: ${{ github.repository }}
          pr: ${{ github.event.pull_request.number }}
          commit_sha: ${{ github.sha }}
          component_pattern: "category: (.*)"
          repo_token: ${{ secrets.GITHUB_TOKEN }} # it has read-only access for forks, should be fine

      - name: Show affected components
        run: |
          echo "${{ toJSON(steps.smart_ci.outputs.affected_components) }}"
        shell: bash